Fix build error: correct system management include and function call
- Fix include from '../utils/system_monitor.h' to '../utils/system_management.h'
- Update health timer callback to use get_system_health_status() which returns a pointer
- Use const system_health_t* health = get_system_health_status() instead of passing by reference
- This fixes the compilation error: 'No such file or directory: ../utils/system_monitor.h'